name: "🐞Bug Form"
description: "convenient?"
title: "<title>"
labels:
  - "Bug"
  - "good first issue"
  - "help wanted"
  - "up-for-grabs"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report:

  - type: textarea
    attributes:
      label: "Description:"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        (Clear/concise).
        Screenshot/Video welcome! (Upload by drag & drop)
    validations:
      required: true

  - type: input
    attributes:
      label: "Steps to reproduce:"
      placeholder: "(Might only happen with a certain feature of ours enabled?)"
    validations:
      required: true

  - type: input
    attributes:
      label: "Since when?"
      placeholder: "Since YouTube changed something? Or since we did?"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: "Does the bug still happen when you log out of YouTube?"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "No? Then please copy your experiment flags list twice:"
      placeholder: |
        (with & without the error to compare) 
        Enter `yt.config_.EXPERIMENT_FLAGS` into the Browser console on YouTube 
        (= F12-Key) (ctrl+U is more clunky) 

  - type: input
    attributes:
      label: "Are any errors shown in the Browser-Console?"
    validations:
      required: no

  - type: dropdown
    id: browsers
    attributes:
      label: "Browser/s:"
      multiple: true
      options:
        - label: "Firefox"
          value: "Firefox"
        - label: "Chrome"
          value: "Chrome"
        - label: "Safari"
          value: "Safari"
        - label: "Brave"
          value: "Brave"
        - label: "Vivaldi"
          value: "Vivaldi"
        - label: "Whale"
          value: "Whale"
        - label: "Edge"
          value: "Edge"
        - label: "Opera"
          value: "Opera"
        - label: "OperaGX"
          value: "OperaGX"
    validations:
      required: false

  - type: input
    attributes:
      label: "Other Browser:"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Before submitting:  Thanks for coming & caring! 
        Sometimes even 3 words are enough for a bug report. 
        Just please check if the issue has already been reported. 
        If so, you can add different/better words to that report.
        [GitHub's issue search](https://github.com/ImprovedTube/ImprovedTube/issues?q=) _(use the link or remove "is:issue is:open" from the search)_
          - _(If this was posted before, you can answer/react there to give it your voice and this also move it up in our lists)_ 
            - _If the status is "closed" (=fixed) recently, then the Browser's stores can be updated soon. If it was already closed months or years ago, then it might have appeared again and must be fixed again.)_

  - type: checkboxes
    attributes:
      label: "Tested as the only active extension? (incognito mode or another browser users):"
      options:
        - label: "Yes"
        - label: "No"

  - type: input
    attributes:
      label: "Expected preferred behavior:"
    validations:
      required: false

  - type: input
    attributes:
      label: "ImprovedTube Version"
      placeholder: "(Written in the Extension header & your Browser's store)"
    validations:
      required: false

  - type: input
    attributes:
      label: "Your Settings (From the Extension's `⋮`-Hamburger menu > Settings > Backup & reset > Export settings)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        (You can remove Blocklist, History Analyzer data - or paste the following in the Browser-Console and hit enter: `(function({analyzer, blocklist, ...a}){return JSON.stringify(a)})(ImprovedTube.storage)`)

  - type: input
    attributes:
      label: "Your YouTube-Document"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        `F12` & copy the whole root element: \<html> in the top [(how?)](https://github.com/code-charity/youtube/wiki/Contributing#Test) (alternative: CTRL+U)  

  - type: input
    attributes:
      label: "OS / Device:"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
         Many thanks & smiles!
