---
name: Wish or Feature request, with BOUNTY PAYMENT
about: Wish or Feature request, with BOUNTY PAYMENT
title: ''
labels: Feature request, good first issue, help wanted, bounty
assignees: ''

---

<!--
(Click PREVIEW to undestand this template) 
   OPTIONALLY fill the table if each point fits in the same line: 
-->

⚬ _REASON / PROBLEM_: 
<!-- (Does your IDEA / feature request relate to a Problem? Which problem is? 
   Ex. I'm always frustrated when [...] )-->

⚬ _WISH / SOLUTION_:    
<!-- (Describe what you'd like 
   (A clear and concise description of what you want to happen). 
   Please consider screenshots or sketches if it makes sense)-->

⚬ _BOUNTY_:  <!-- How much are you willing to donate / pay for this? and by what method? -->

 ⚬ _ALTERNATIVES_: 
<!-- (Describe what you've considered: 
   Alternative solutions or features, you'd consider as equal or inferior). -->

 ⚬ _RELEVANCE / SCOPE_: 
<!-- (Would this be good by for everybody by default? (hypothetically). 
   Estimate how many percent of our users (or all youtube users) should/would use your idea? ) -->

⚬ _"SIDE EFFECTS"_:   
<!-- (Is there any conflict with any other feature? 
   Who might NOT want this?(How many percent of users could be bothered by it even filling space in our menu?)--> 

⚬ _CONTEXT_:
<!-- any other context. -->

Thank you!

SHORT Table    | (Summary)     
-------------  | -------------   
*Problem*      |       
*Solution*     | <!-- TYPE HERE, 1 line each) -->         
*Alternatives* |         
*Scope*        |           
*Side effects* |        
*Context*      |
